# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160518_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='officer',
        ),
        migrations.AddField(
            model_name='brother',
            name='officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
