# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='password',
            field=models.CharField(default='passionfruit', max_length=50),
        ),
    ]
