# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160526_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
