# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160528_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.Chapter'),
        ),
    ]
