# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160528_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='brother', serialize=False, to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='app.Event'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='app.Meeting'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hours', serialize=False, to='app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pledge', serialize=False, to='app.UserProfile'),
        ),
    ]
