# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160529_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chapter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.Chapter'),
        ),
    ]
