# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='events',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='meetings',
        ),
        migrations.AddField(
            model_name='hours',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='app.Event'),
        ),
        migrations.AddField(
            model_name='hours',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='app.Meeting'),
        ),
    ]
