# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160531_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother',
            name='officer',
        ),
    ]
