# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_brother_officer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['chapter_id'], 'permissions': ('officer', 'Is an officer')},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
