# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160602_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['chapter_id'], 'permissions': (('officer', 'Is an officer'),)},
        ),
    ]
