# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 22:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160602_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='email',
        ),
        migrations.AddField(
            model_name='demographics',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number needs to be in format 123456789, up to 15 characters accepted', regex='^\\d{9-15}$')]),
        ),
    ]
