# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 22:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160603_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number needs to be in format 123456789, up to 15 characters accepted', regex='^[0-9]{9-15}$')]),
        ),
    ]
