# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160603_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='chapter_id',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='demographics',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number needs to be in format 123456789, up to 15 characters accepted', regex='^[0-9]{9,15}$')]),
        ),
    ]
