# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160604_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('brother', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='app.Pledge')),
            ],
            options={
                'ordering': ['pledge'],
            },
        ),
    ]
