# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='e_absences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brother',
            name='u_absences',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
