# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160615_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('excuse_id', models.AutoField(primary_key=True, serialize=False)),
                ('excuse', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='app.Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='app.UserProfile')),
            ],
        ),
    ]
